#!/usr/bin/env python3
import sys
import pyaudio
import numpy as np

def collect_info(f):
	print(f.read())
	count = 0
	tempo = 'tempo'
	class track:
		tempo = 0
		tracks = ''
	while 
	if tempo in line:
		for word in line.split():
			if word.isdigit():
				track.tempo = int(word)
	while True:
		count += 1
		line = f.readline()
		if not line:
			break
	

	print(track.tempo)

def main(argv, argc):
	#//print 'Number of arguments:', len(sys.argv), 'arguments.'
	#print 'Argument List:', str(sys.argv)
	if argc == 2:
		f = open(argv[1], "r")
		collect_info(f)
		
	else:
		print("Usage: ./minisynth /path/to/file")

if __name__ == "__main__":
	main(sys.argv, len(sys.argv))
